# -*- coding: UTF-8 -*-
GRUPOS_ETARIOS = (
    ('<18', 'Menor de 18 años'),
    ('18-24', '18 a 24 años'),
    ('25-34', '25 a 34 años'), 
    ('35-44', '35 a 44 años'), 
    ('45-54', '45 a 54 años'), 
    ('55-64', '55 a 64 años'), 
    ('>65', '25 a 34 años'),
)

SEXOS = (
    ('','---Seleccione su sexo---'),
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'),
    ('Otro', 'Otro'),
)

CIUDADES = (
    ('','---Seleccione su ciudad de residencia---'),
    (u'Asunción', u'Asunción'),
    (u'Fuera del País', u'Fuera del País'), 
    (u'3 de Mayo - Caazapá', u'3 de Mayo - Caazapá'),
    (u'Abaí - Caazapá', u'Abaí - Caazapá'),
    (u'Acahay - Paraguarí', u'Acahay - Paraguarí'),
    (u'Alberdi - Ñeembucú', u'Alberdi - Ñeembucú'),
    (u'Alto Verá - Itapúa', u'Alto Verá - Itapúa'),
    (u'Altos - Cordillera', u'Altos - Cordillera'),
    (u'Antequera - San Pedro', u'Antequera - San Pedro'),
    (u'Areguá - Central', u'Areguá - Central'),
    (u'Arroyos y Esteros - Cordillera', u'Arroyos y Esteros - Cordillera'),
    (u'Atyrá - Cordillera', u'Atyrá - Cordillera'),
    (u'Ayolas - Misiones', u'Ayolas - Misiones'),
    (u'Azotey - Concepción', u'Azotey - Concepción'),
    (u'Bahía Negra - Alto Paraguay', u'Bahía Negra - Alto Paraguay'),
    (u'Bella Vista - Amambay', u'Bella Vista - Amambay'),
    (u'Bella Vista - Itapúa', u'Bella Vista - Itapúa'),
    (u'Belén - Concepción', u'Belén - Concepción'),
    (u'Benjamín Aceval - Presidente Hayes', u'Benjamín Aceval - Presidente Hayes'),
    (u'Borja - Guairá', u'Borja - Guairá'),
    (u'Buena Vista - Caazapá', u'Buena Vista - Caazapá'),
    (u'Caacupé - Cordillera', u'Caacupé - Cordillera'),
    (u'Caaguazú - Caaguazú', u'Caaguazú - Caaguazú'),
    (u'Caapucú - Paraguarí', u'Caapucú - Paraguarí'),
    (u'Caazapá - Caazapá', u'Caazapá - Caazapá'),
    (u'Cambyretá - Itapúa', u'Cambyretá - Itapúa'),
    (u'Capiatá - Central', u'Capiatá - Central'),
    (u'Capiibary - San Pedro', u'Capiibary - San Pedro'),
    (u'Capitán Bado - Amambay', u'Capitán Bado - Amambay'),
    (u'Capitán Meza - Itapúa', u'Capitán Meza - Itapúa'),
    (u'Capitán Miranda - Itapúa', u'Capitán Miranda - Itapúa'),
    (u'Caraguatay - Cordillera', u'Caraguatay - Cordillera'),
    (u'Carapeguá - Paraguarí', u'Carapeguá - Paraguarí'),
    (u'Carayaó - Caaguazú', u'Carayaó - Caaguazú'),
    (u'Carlos Antonio López - Itapúa', u'Carlos Antonio López - Itapúa'),
    (u'Carmelo Peralta - Alto Paraguay', u'Carmelo Peralta - Alto Paraguay'),
    (u'Carmen del Paraná - Itapúa', u'Carmen del Paraná - Itapúa'),
    (u'Cerrito - Ñeembucú', u'Cerrito - Ñeembucú'),
    (u'Choré - San Pedro', u'Choré - San Pedro'),
    (u'Ciudad del Este - Alto Paraná', u'Ciudad del Este - Alto Paraná'),
    (u'Colonia Independencia - Guairá', u'Colonia Independencia - Guairá'),
    (u'Concepción - Concepción', u'Concepción - Concepción'),
    (u'Coronel Bogado - Itapúa', u'Coronel Bogado - Itapúa'),
    (u'Coronel Martínez - Guairá', u'Coronel Martínez - Guairá'),
    (u'Coronel Oviedo - Caaguazú', u'Coronel Oviedo - Caaguazú'),
    (u'Corpus Christi - Canindeyú', u'Corpus Christi - Canindeyú'),
    (u'Curuguaty - Canindeyú', u'Curuguaty - Canindeyú'),
    (u'Desmochados - Ñeembucú', u'Desmochados - Ñeembucú'),
    (u'Doctor Cecilio Báez - Caaguazú', u'Doctor Cecilio Báez - Caaguazú'),
    (u'Doctor J. Eulogio Estigarribia - Caaguazú', u'Doctor J. Eulogio Estigarribia - Caaguazú'),
    (u'Doctor Juan León Mallorquín - Alto Paraná', u'Doctor Juan León Mallorquín - Alto Paraná'),
    (u'Doctor Juan Manuel Frutos - Caaguazú', u'Doctor Juan Manuel Frutos - Caaguazú'),
    (u'Doctor Moisés S. Bertoni - Caazapá', u'Doctor Moisés S. Bertoni - Caazapá'),
    (u'Doctor Raúl Peña - Alto Paraná', u'Doctor Raúl Peña - Alto Paraná'),
    (u'Domingo Martínez de Irala - Alto Paraná', u'Domingo Martínez de Irala - Alto Paraná'),
    (u'Dr. Bottrell - Guairá', u'Dr. Bottrell - Guairá'),
    (u'Dr. José Falcón - Presidente Hayes', u'Dr. José Falcón - Presidente Hayes'),
    (u'Edelira - Itapúa', u'Edelira - Itapúa'),
    (u'Emboscada - Cordillera', u'Emboscada - Cordillera'),
    (u'Encarnación - Itapúa', u'Encarnación - Itapúa'),
    (u'Escobar - Paraguarí', u'Escobar - Paraguarí'),
    (u'Eusebio Ayala - Cordillera', u'Eusebio Ayala - Cordillera'),
    (u'Fassardi - Guairá', u'Fassardi - Guairá'),
    (u'Fernando de la Mora - Central', u'Fernando de la Mora - Central'),
    (u'Filadelfia - Boquerón', u'Filadelfia - Boquerón'),
    (u'Fram - Itapúa', u'Fram - Itapúa'),
    (u'Fuerte Olimpo - Alto Paraguay', u'Fuerte Olimpo - Alto Paraguay'),
    (u'Fulgencio Yegros - Caazapá', u'Fulgencio Yegros - Caazapá'),
    (u'Félix Pérez Cardozo - Guairá', u'Félix Pérez Cardozo - Guairá'),
    (u'Garay - Guairá', u'Garay - Guairá'),
    (u'General Artigas - Itapúa', u'General Artigas - Itapúa'),
    (u'General Delgado - Itapúa', u'General Delgado - Itapúa'),
    (u'General Elizardo Aquino - San Pedro', u'General Elizardo Aquino - San Pedro'),
    (u'General Higinio Morínigo - Caazapá', u'General Higinio Morínigo - Caazapá'),
    (u'General Isidoro Resquín - San Pedro', u'General Isidoro Resquín - San Pedro'),
    (u'General José Eduvigis Díaz - Ñeembucú', u'General José Eduvigis Díaz - Ñeembucú'),
    (u'General José María Bruguez - Presidente Hayes', u'General José María Bruguez - Presidente Hayes'),
    (u'Gral. Bernardino Caballero - Paraguarí', u'Gral. Bernardino Caballero - Paraguarí'),
    (u'Gral. Francisco Caballero Álvarez - Canindeyú', u'Gral. Francisco Caballero Álvarez - Canindeyú'),
    (u'Guarambaré - Central', u'Guarambaré - Central'),
    (u'Guayaibí - San Pedro', u'Guayaibí - San Pedro'),
    (u'Guazú Cuá - Ñeembucú', u'Guazú Cuá - Ñeembucú'),
    (u'Hernandarias - Alto Paraná', u'Hernandarias - Alto Paraná'),
    (u'Hohenau - Itapúa', u'Hohenau - Itapúa'),
    (u'Horqueta - Concepción', u'Horqueta - Concepción'),
    (u'Humaitá - Ñeembucú', u'Humaitá - Ñeembucú'),
    (u'Iruña - Alto Paraná', u'Iruña - Alto Paraná'),
    (u'Isla Pucú - Cordillera', u'Isla Pucú - Cordillera'),
    (u'Isla Umbú - Ñeembucú', u'Isla Umbú - Ñeembucú'),
    (u'Itacurubí de la Cordillera - Cordillera', u'Itacurubí de la Cordillera - Cordillera'),
    (u'Itacurubí del Rosario - San Pedro', u'Itacurubí del Rosario - San Pedro'),
    (u'Itakyry - Alto Paraná', u'Itakyry - Alto Paraná'),
    (u'Itanará - Canindeyú', u'Itanará - Canindeyú'),
    (u'Itapé - Guairá', u'Itapé - Guairá'),
    (u'Itapúa Poty - Itapúa', u'Itapúa Poty - Itapúa'),
    (u'Itauguá - Central', u'Itauguá - Central'),
    (u'Iturbe - Guairá', u'Iturbe - Guairá'),
    (u'Itá - Central', u'Itá - Central'),
    (u'Jesús - Itapúa', u'Jesús - Itapúa'),
    (u'José Domingo Ocampos - Caaguazú', u'José Domingo Ocampos - Caaguazú'),
    (u'José Leandro Oviedo - Itapúa', u'José Leandro Oviedo - Itapúa'),
    (u'Juan de Mena - Cordillera', u'Juan de Mena - Cordillera'),
    (u"Juan Emilio O'Leary - Alto Paraná", u"Juan Emilio O'Leary - Alto Paraná"),
    (u'Julián Augusto Saldívar - Central', u'Julián Augusto Saldívar - Central'),
    (u'Karapaí - Amambay', u'Karapaí - Amambay'),
    (u'Katueté - Canindeyú', u'Katueté - Canindeyú'),
    (u'La Colmena - Paraguarí', u'La Colmena - Paraguarí'),
    (u'La Paloma - Canindeyú', u'La Paloma - Canindeyú'),
    (u'La Pastora - Caaguazú', u'La Pastora - Caaguazú'),
    (u'La Paz - Itapúa', u'La Paz - Itapúa'),
    (u'Lambaré - Central', u'Lambaré - Central'),
    (u'Laureles - Ñeembucú', u'Laureles - Ñeembucú'),
    (u'Liberación - San Pedro', u'Liberación - San Pedro'),
    (u'Lima - San Pedro', u'Lima - San Pedro'),
    (u'Limpio - Central', u'Limpio - Central'),
    (u'Loma Grande - Cordillera', u'Loma Grande - Cordillera'),
    (u'Loma Plata - Boquerón', u'Loma Plata - Boquerón'),
    (u'Loreto - Concepción', u'Loreto - Concepción'),
    (u'Los Cedrales - Alto Paraná', u'Los Cedrales - Alto Paraná'),
    (u'Luque - Central', u'Luque - Central'),
    (u'Maciel - Caazapá', u'Maciel - Caazapá'),
    (u'Mariano Roque Alonso - Central', u'Mariano Roque Alonso - Central'),
    (u'Mariscal Estigarribia - Boquerón', u'Mariscal Estigarribia - Boquerón'),
    (u'Mayor José J. Martínez - Ñeembucú', u'Mayor José J. Martínez - Ñeembucú'),
    (u'Mayor Otaño - Itapúa', u'Mayor Otaño - Itapúa'),
    (u'Mbaracayú - Alto Paraná', u'Mbaracayú - Alto Paraná'),
    (u'Mbocayaty - Guairá', u'Mbocayaty - Guairá'),
    (u'Mbocayaty del Yhaguy - Cordillera', u'Mbocayaty del Yhaguy - Cordillera'),
    (u'Mbuyapey - Paraguarí', u'Mbuyapey - Paraguarí'),
    (u'Mcal. Francisco S. López - Caaguazú', u'Mcal. Francisco S. López - Caaguazú'),
    (u'Minga Guazú - Alto Paraná', u'Minga Guazú - Alto Paraná'),
    (u'Minga Porá - Alto Paraná', u'Minga Porá - Alto Paraná'),
    (u'Nanawa - Presidente Hayes', u'Nanawa - Presidente Hayes'),
    (u'Naranjal - Alto Paraná', u'Naranjal - Alto Paraná'),
    (u'Natalicio Talavera - Guairá', u'Natalicio Talavera - Guairá'),
    (u'Natalio - Itapúa', u'Natalio - Itapúa'),
    (u'Nueva Alborada - Itapúa', u'Nueva Alborada - Itapúa'),
    (u'Nueva Colombia - Cordillera', u'Nueva Colombia - Cordillera'),
    (u'Nueva Esperanza - Canindeyú', u'Nueva Esperanza - Canindeyú'),
    (u'Nueva Germania - San Pedro', u'Nueva Germania - San Pedro'),
    (u'Nueva Italia - Central', u'Nueva Italia - Central'),
    (u'Nueva Londres - Caaguazú', u'Nueva Londres - Caaguazú'),
    (u'Nueva Toledo - Caaguazú', u'Nueva Toledo - Caaguazú'),
    (u'Ñacunday - Alto Paraná', u'Ñacunday - Alto Paraná'),
    (u'Ñemby - Central', u'Ñemby - Central'),
    (u'Ñumí - Guairá', u'Ñumí - Guairá'),
    (u'Obligado - Itapúa', u'Obligado - Itapúa'),
    (u'Paraguarí - Paraguarí', u'Paraguarí - Paraguarí'),
    (u'Paso Barreto - Concepción', u'Paso Barreto - Concepción'),
    (u'Paso de Patria - Ñeembucú', u'Paso de Patria - Ñeembucú'),
    (u'Paso Yobái - Guairá', u'Paso Yobái - Guairá'),
    (u'Pedro Juan Caballero - Amambay', u'Pedro Juan Caballero - Amambay'),
    (u'Pilar - Ñeembucú', u'Pilar - Ñeembucú'),
    (u'Pirapó - Itapúa', u'Pirapó - Itapúa'),
    (u'Pirayú - Paraguarí', u'Pirayú - Paraguarí'),
    (u'Piribebuy - Cordillera', u'Piribebuy - Cordillera'),
    (u'Presidente Franco - Alto Paraná', u'Presidente Franco - Alto Paraná'),
    (u'Primero de Marzo - Cordillera', u'Primero de Marzo - Cordillera'),
    (u'Puerto Casado - Alto Paraguay', u'Puerto Casado - Alto Paraguay'),
    (u'Puerto Pinasco - Presidente Hayes', u'Puerto Pinasco - Presidente Hayes'),
    (u'Quiindy - Paraguarí', u'Quiindy - Paraguarí'),
    (u'Quyquyhó - Paraguarí', u'Quyquyhó - Paraguarí'),
    (u'R. I. Tres Corrales - Caaguazú', u'R. I. Tres Corrales - Caaguazú'),
    (u'Raúl Arsenio Oviedo - Caaguazú', u'Raúl Arsenio Oviedo - Caaguazú'),
    (u'Repatriación - Caaguazú', u'Repatriación - Caaguazú'),
    (u'Salto del Guairá - Canindeyú', u'Salto del Guairá - Canindeyú'),
    (u'San Alberto - Alto Paraná', u'San Alberto - Alto Paraná'),
    (u'San Alfredo - Concepción', u'San Alfredo - Concepción'),
    (u'San Antonio - Central', u'San Antonio - Central'),
    (u'San Bernardino - Cordillera', u'San Bernardino - Cordillera'),
    (u'San Carlos del Apa - Concepción', u'San Carlos del Apa - Concepción'),
    (u'San Cosme y Damián - Itapúa', u'San Cosme y Damián - Itapúa'),
    (u'San Cristóbal - Alto Paraná', u'San Cristóbal - Alto Paraná'),
    (u'San Estanislao - San Pedro', u'San Estanislao - San Pedro'),
    (u'San Ignacio - Misiones', u'San Ignacio - Misiones'),
    (u'San Joaquín - Caaguazú', u'San Joaquín - Caaguazú'),
    (u'San José de los Arroyos - Caaguazú', u'San José de los Arroyos - Caaguazú'),
    (u'San José Obrero - Cordillera', u'San José Obrero - Cordillera'),
    (u'San Juan Bautista del Ñeembucú - Ñeembucú', u'San Juan Bautista del Ñeembucú - Ñeembucú'),
    (u'San Juan Bautista. - Misiones', u'San Juan Bautista. - Misiones'),
    (u'San Juan del Paraná - Itapúa', u'San Juan del Paraná - Itapúa'),
    (u'San Juan Nepomuceno - Caazapá', u'San Juan Nepomuceno - Caazapá'),
    (u'San Lorenzo - Central', u'San Lorenzo - Central'),
    (u'San Lázaro - Concepción', u'San Lázaro - Concepción'),
    (u'San Miguel - Misiones', u'San Miguel - Misiones'),
    (u'San Pablo - San Pedro', u'San Pablo - San Pedro'),
    (u'San Patricio - Misiones', u'San Patricio - Misiones'),
    (u'San Pedro - San Pedro', u'San Pedro - San Pedro'),
    (u'San Pedro del Paraná - Itapúa', u'San Pedro del Paraná - Itapúa'),
    (u'San Rafael del Paraná - Itapúa', u'San Rafael del Paraná - Itapúa'),
    (u'San Roque González de Santa Cruz - Paraguarí', u'San Roque González de Santa Cruz - Paraguarí'),
    (u'San Salvador - Guairá', u'San Salvador - Guairá'),
    (u'Santa Elena - Cordillera', u'Santa Elena - Cordillera'),
    (u'Santa Fe del Paraná - Alto Paraná', u'Santa Fe del Paraná - Alto Paraná'),
    (u'Santa María - Misiones', u'Santa María - Misiones'),
    (u'Santa Rita - Alto Paraná', u'Santa Rita - Alto Paraná'),
    (u'Santa Rosa - Misiones', u'Santa Rosa - Misiones'),
    (u'Santa Rosa del Aguaray - San Pedro', u'Santa Rosa del Aguaray - San Pedro'),
    (u'Santa Rosa del Mbutuy - Caaguazú', u'Santa Rosa del Mbutuy - Caaguazú'),
    (u'Santa Rosa del Monday - Alto Paraná', u'Santa Rosa del Monday - Alto Paraná'),
    (u'Santiago - Misiones', u'Santiago - Misiones'),
    (u'Sapucai - Paraguarí', u'Sapucai - Paraguarí'),
    (u'Sargento José Félix López - Concepción', u'Sargento José Félix López - Concepción'),
    (u'Simón Bolívar - Caaguazú', u'Simón Bolívar - Caaguazú'),
    (u'Tacuaras - Ñeembucú', u'Tacuaras - Ñeembucú'),
    (u'Tacuatí - San Pedro', u'Tacuatí - San Pedro'),
    (u'Tavapy - Alto Paraná', u'Tavapy - Alto Paraná'),
    (u'Tavaí - Caazapá', u'Tavaí - Caazapá'),
    (u'Tebicuary - Guairá', u'Tebicuary - Guairá'),
    (u'Tebicuarymí - Paraguarí', u'Tebicuarymí - Paraguarí'),
    (u'Tembiaporá - Caaguazú', u'Tembiaporá - Caaguazú'),
    (u'Tobatí - Cordillera', u'Tobatí - Cordillera'),
    (u'Tomás Romero Pereira - Itapúa', u'Tomás Romero Pereira - Itapúa'),
    (u'Tres de Febrero - Caaguazú', u'Tres de Febrero - Caaguazú'),
    (u'Trinidad - Itapúa', u'Trinidad - Itapúa'),
    (u'Troche - Guairá', u'Troche - Guairá'),
    (u'Tte. Esteban Martínez - Presidente Hayes', u'Tte. Esteban Martínez - Presidente Hayes'),
    (u'Tte. Irala Fernández - Presidente Hayes', u'Tte. Irala Fernández - Presidente Hayes'),
    (u'Unión - San Pedro', u'Unión - San Pedro'),
    (u'Valenzuela - Cordillera', u'Valenzuela - Cordillera'),
    (u'Vaquería - Caaguazú', u'Vaquería - Caaguazú'),
    (u'Veinticinco de Diciembre - San Pedro', u'Veinticinco de Diciembre - San Pedro'),
    (u'Villa del Rosario - San Pedro', u'Villa del Rosario - San Pedro'),
    (u'Villa Elisa - Central', u'Villa Elisa - Central'),
    (u'Villa Florida - Misiones', u'Villa Florida - Misiones'),
    (u'Villa Franca - Ñeembucú', u'Villa Franca - Ñeembucú'),
    (u'Villa Hayes - Presidente Hayes', u'Villa Hayes - Presidente Hayes'),
    (u'Villa Oliva - Ñeembucú', u'Villa Oliva - Ñeembucú'),
    (u'Villa Ygatimí - Canindeyú', u'Villa Ygatimí - Canindeyú'),
    (u'Villalbín - Ñeembucú', u'Villalbín - Ñeembucú'),
    (u'Villarrica - Guairá', u'Villarrica - Guairá'),
    (u'Villeta - Central', u'Villeta - Central'),
    (u'Yabebyry - Misiones', u'Yabebyry - Misiones'),
    (u'Yaguarón - Paraguarí', u'Yaguarón - Paraguarí'),
    (u'Yasy Cañy - Canindeyú', u'Yasy Cañy - Canindeyú'),
    (u'Yataity - Guairá', u'Yataity - Guairá'),
    (u'Yataity del Norte - San Pedro', u'Yataity del Norte - San Pedro'),
    (u'Yatytay - Itapúa', u'Yatytay - Itapúa'),
    (u'Yby Pytá - Canindeyú', u'Yby Pytá - Canindeyú'),
    (u'Yby Yaú - Concepción', u'Yby Yaú - Concepción'),
    (u'Ybycuí - Paraguarí', u'Ybycuí - Paraguarí'),
    (u'Ybyrarovaná - Canindeyú', u'Ybyrarovaná - Canindeyú'),
    (u'Ybytymí - Paraguarí', u'Ybytymí - Paraguarí'),
    (u'Yguazú - Alto Paraná', u'Yguazú - Alto Paraná'),
    (u'Yhú - Caaguazú', u'Yhú - Caaguazú'),
    (u'Ypacaraí - Central', u'Ypacaraí - Central'),
    (u'Ypané - Central', u'Ypané - Central'),
    (u'Ypejhú - Canindeyú', u'Ypejhú - Canindeyú'),
    (u'Yrybucuá - San Pedro', u'Yrybucuá - San Pedro'),
    (u'Yuty - Caazapá', u'Yuty - Caazapá'),
    (u'Zanja Pytá - Amambay', u'Zanja Pytá - Amambay')
)
